[profile.default]
src = "src"
out = "out"
test = "test"
script = "script"
libs = ["lib", "node_modules"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
fs_permissions = [
    { access = "read", path = "../data" },
    { access = "read", path = "./out" },
    { access = "read-write", path = "./deployment.addresses.json" },
]

[fuzz]
runs = 256
